/* ============================================================
   Massage 4 Beauty — site content in 3 languages.
   Edit text and prices here. Prices are numbers (CZK).
   ============================================================ */
window.CONTENT = {
  contact: {
    address: "Děkanská vinice I 819/16, Praha 4 – Nusle",
    phone: "+420 721 761 411",
    email: "beautymassage.prague@gmail.com",
  },

  /* -------------------- ENGLISH -------------------- */
  en: {
    currency: (p) => p.toLocaleString("en-US") + " CZK",
    minLabel: "min",
    strings: {
      navServices: "Services", navPrices: "Price list", navAbout: "About", navContact: "Contact",
      heroEyebrow: "Massage 4 Beauty · Prague",
      heroH1: "Healthy, glowing skin begins with a gentle touch",
      heroSub: "Professional facial and body massage by Ludmila — over ten years of experience, personalised techniques, visible results.",
      ctaBook: "Book an appointment", ctaPrices: "View price list",
      aboutEyebrow: "About the master", aboutName: "Ludmila Yemelianova",
      aboutWelcome: "Welcome to Massage 4 Beauty.",
      aboutP1: "My name is Ludmila, and for over ten years I have been helping my clients find harmony, relaxation and natural beauty through professional facial and body massage.",
      aboutP2: "Every treatment is unique and tailored to your individual needs. Whether you are looking for deep relaxation, relief from tension, body recovery or natural skin rejuvenation, together we will find the care that is right for you.",
      aboutP3: "My goal is that after your treatment you leave not only feeling light and rested, but also with renewed energy, healthier skin and a greater sense of harmony between body and soul.",
      aboutCaption: "Certified massage therapist · Prague",
      pricesEyebrow: "Price list", pricesH2: "Treatments & pricing",
      groupFace: "Face", groupBody: "Body",
      contactEyebrow: "Contact", contactH2: "Book your visit",
      contactSub: "Leave a message and we'll help you pick the right treatment and a convenient date and time.",
      lblAddress: "Address", lblPhone: "Phone", lblEmail: "Email",
      fName: "Your name", fContact: "Phone or email", fTreatment: "Treatment (optional)", fMessage: "Message", fSend: "Send request",
      formThanks: "Thank you! We'll get back to you shortly.",
      footerCopy: "© 2026 Beauty Massage by Ludmila Yemelianova",
      privacyLink: "Privacy Policy",
      privacyEyebrow: "Legal information",
      privacyH1: "Privacy Policy (GDPR)",
      privacyIntro1: "The data controller is Liudmyla Yemelianova, trading under the brand Massage 4 Beauty, Company ID: 23110716.",
      privacyIntro2: "We process your personal data including: full name, phone number, email address, and any other information provided in the booking form.",
      privacyH2Purpose: "Purpose of data processing",
      privacyP1: "creating and managing bookings",
      privacyP2: "communication regarding appointments",
      privacyP3: "providing massage and related services",
      privacyP4: "handling changes or cancellations of bookings",
      privacyH2Legal: "Legal basis for processing",
      privacyL1: "performance of a contract (booking and provision of services)",
      privacyL2: "legitimate interest of the controller",
      privacyH2Retention: "Data retention period",
      privacyRetention: "We retain personal data for as long as necessary, typically for the duration of the relationship and for a maximum of 3 years after the last booking.",
      privacyH2Recipients: "Recipients of data",
      privacyRecipients: "Personal data is not shared with third parties, except for technical service providers.",
      privacyH2Marketing: "Marketing consent (optional)",
      privacyPhotoLabel: "Consent to use of photographs",
      privacyCommLabel: "Consent to marketing communication",
      privacyH2Contact: "Contact",
      privacyContactNote: "For any questions regarding data protection, please contact us via the contact details provided on this website.",
    },
    facial: [
      { name: "Facial Ritual — Neck, Décolleté, Face & Head", desc: "A deep, multi-level procedure releasing muscle tension, improving blood and lymph circulation, and naturally restoring skin tone.", min: 60, price: 1600 },
      { name: "Myofascial Facial Massage", desc: "Intensive work with facial muscles, including the inner cheek area. Sculpts the contour, reduces nasolabial folds and sagging.", min: 45, price: 1300 },
      { name: "Neck, Décolleté & Hands Massage", desc: "Improves blood flow and lymph drainage while relaxing the muscles of the neck and chest area.", min: 60, price: 1200 },
      { name: "Lifting Massage", desc: "Reduces puffiness under the eyes, improves lymphatic drainage, gives the face a lighter, more lifted appearance.", min: 45, price: 1000 },
      { name: "Vacuum (Cupping) Facial Massage", desc: "Focuses on muscle toning and strengthening, enhancing skin elasticity and facial contours.", min: 45, price: 800 },
      { name: "Gua Sha Massage", desc: "A draining, contouring treatment that relieves tension and enhances skin tone using traditional Gua Sha techniques.", min: 45, price: 800 },
      { name: "Buccal Massage", desc: "A facial massage technique performed both externally and through the oral cavity. Helps relieve facial muscle tension, improve microcirculation, increase skin tone and define facial contours. Promotes natural rejuvenation and deep relaxation.", min: 30, price: 800 },
      { name: "Alginate Mask · add-on", desc: "Reduces swelling and redness, evens out skin tone, deeply moisturises and soothes the skin.", min: 15, price: 250 },
      { name: "Head Massage", desc: "Relaxes the nervous system, stimulates hair growth, reduces stress and helps prevent headaches.", min: 30, price: 600 },
    ],
    body: [
      { name: "Sports Massage", desc: "Muscle recovery after exertion and intense training — relieves tension, reduces soreness, speeds up recovery.", min: 60, price: 1600 },
      { name: "Massage with Bamboo Brooms", desc: "The body is gently warmed and massaged with bamboo brooms, improving circulation, lymph flow and skin tone.", min: 60, price: 1600 },
      { name: "Lymphatic Drainage Massage", desc: "Improves lymph flow, reduces swelling and puffiness, supports metabolism and overall well-being.", min: 60, price: 1500 },
      { name: "Anti-Cellulite Massage", desc: "Intensive work on problem areas — improves circulation, stimulates fat breakdown, increases skin firmness.", min: 45, price: 1500 },
      { name: "Honey Massage", desc: "Natural honey cleanses the skin and activates metabolism, leaving skin smoother, softer and refreshed.", min: 60, price: 1500 },
      { name: "Classic Massage", desc: "A universal procedure for relaxation and overall wellness — improves circulation and restores energy.", min: 60, price: 1300 },
      { name: "Aroma Massage", desc: "Classic techniques with individually selected essential oils — deeply relaxing, lowers stress, improves mood.", min: 60, price: 1300 },
      { name: "Vacuum (Cupping) Body Massage", desc: "Suction cups actively stimulate blood and lymph circulation — reduces swelling, fights cellulite.", min: 45, price: 1200 },
      { name: "Back Massage", desc: "Relieves tension in the back muscles, reduces pain and fatigue, improves circulation and brings deep relaxation and a sense of lightness in the body.", min: 30, price: 700 },
      { name: "Reflexology Foot Massage", desc: "A technique targeting biologically active points and zones connected to internal organs and body systems. Stimulation of these points activates natural regeneration processes and overall relaxation.", min: 30, price: 600 },
    ],
  },

  /* -------------------- ČEŠTINA -------------------- */
  cs: {
    currency: (p) => p.toLocaleString("cs-CZ").replace(/\u00a0/g, " ") + " Kč",
    minLabel: "min",
    strings: {
      navServices: "Služby", navPrices: "Ceník", navAbout: "O mně", navContact: "Kontakt",
      heroEyebrow: "Massage 4 Beauty · Praha",
      heroH1: "Zdravá, zářivá pleť začíná jemným dotekem",
      heroSub: "Dopřejte si chvíli jen pro sebe. Relaxační masáže v příjemném prostředí, které pomáhají uvolnit tělo, mysl i každodenní stres.",
      ctaBook: "Objednat se", ctaPrices: "Zobrazit ceník",
      aboutEyebrow: "O mně", aboutName: "Ludmila Yemelianova",
      aboutWelcome: "Vítejte v Massage 4 Beauty.",
      aboutP1: "Jmenuji se Ludmila a již více než deset let pomáhám svým klientům nacházet harmonii, relaxaci a přirozenou krásu prostřednictvím profesionálních masáží obličeje a těla.",
      aboutP2: "Každá procedura je jedinečná a přizpůsobena vašim individuálním potřebám. Ať hledáte hlubokou relaxaci, úlevu od napětí, regeneraci organismu nebo přirozené omlazení pleti, společně vybereme péči, která je určena přímo pro vás.",
      aboutP3: "Mým cílem je, abyste po proceduře odcházeli nejen s pocitem lehkosti a odpočinku, ale také s novou energií, zdravější pletí a větší harmonií těla i duše.",
      aboutCaption: "Certifikovaná masérka · Praha",
      pricesEyebrow: "Ceník", pricesH2: "Procedury a ceny",
      groupFace: "Obličej", groupBody: "Tělo",
      contactEyebrow: "Kontakt", contactH2: "Objednejte se",
      contactSub: "Napište nám a pomůžeme vám vybrat vhodnou proceduru i termín návštěvy.",
      lblAddress: "Adresa", lblPhone: "Telefon", lblEmail: "E-mail",
      fName: "Vaše jméno", fContact: "Telefon nebo e-mail", fTreatment: "Procedura (volitelné)", fMessage: "Zpráva", fSend: "Odeslat poptávku",
      formThanks: "Děkujeme! Brzy se vám ozveme.",
      footerCopy: "© 2026 Beauty Massage · Ludmila Yemelianova",
      privacyLink: "Ochrana osobních údajů",
      privacyEyebrow: "Právní informace",
      privacyH1: "Ochrana osobních údajů (GDPR)",
      privacyIntro1: "Správcem osobních údajů je Liudmyla Yemelianova, podnikající pod značkou Massage 4 Beauty, IČO: 23110716.",
      privacyIntro2: "Zpracováváme vaše osobní údaje v rozsahu: jméno a příjmení, telefonní číslo, e-mailová adresa a případně další údaje uvedené v rezervačním formuláři.",
      privacyH2Purpose: "Účel zpracování údajů",
      privacyP1: "vytvoření a správa rezervace",
      privacyP2: "komunikace ohledně termínu",
      privacyP3: "poskytování masážních a souvisejících služeb",
      privacyP4: "řešení změn nebo zrušení rezervace",
      privacyH2Legal: "Právní základ zpracování",
      privacyL1: "plnění smlouvy (rezervace a poskytnutí služby)",
      privacyL2: "oprávněný zájem správce",
      privacyH2Retention: "Doba uchování údajů",
      privacyRetention: "Osobní údaje uchováváme po dobu nezbytně nutnou, obvykle po dobu trvání spolupráce a maximálně 3 roky po poslední rezervaci.",
      privacyH2Recipients: "Příjemci údajů",
      privacyRecipients: "Osobní údaje nejsou poskytovány třetím stranám, s výjimkou technických poskytovatelů.",
      privacyH2Marketing: "Marketingová souhlasná ujednání (volitelné)",
      privacyPhotoLabel: "Souhlas s použitím fotografií",
      privacyCommLabel: "Souhlas s marketingovou komunikací",
      privacyH2Contact: "Kontakt",
      privacyContactNote: "V případě dotazů týkajících se ochrany osobních údajů nás můžete kontaktovat prostřednictvím kontaktních údajů uvedených na webových stránkách.",
    },
    facial: [
      { name: "Rituál pro obličej — krk, dekolt, obličej a hlava", desc: "Hluboká vícevrstvá procedura uvolňující svalové napětí, zlepšující krevní i lymfatický oběh a přirozeně obnovující tonus pleti.", min: 60, price: 1600 },
      { name: "Myofasciální masáž obličeje", desc: "Intenzivní práce s obličejovými svaly včetně vnitřní strany tváří. Modeluje konturu, redukuje nosoretní rýhy a povadlost.", min: 45, price: 1300 },
      { name: "Masáž krku, dekoltu a rukou", desc: "Zlepšuje prokrvení a lymfatickou drenáž a uvolňuje svaly krku a hrudníku.", min: 60, price: 1200 },
      { name: "Liftingová masáž", desc: "Redukuje otoky pod očima, zlepšuje lymfatickou drenáž a dodává obličeji lehčí, vypnutější vzhled.", min: 45, price: 1000 },
      { name: "Vakuová (baňková) masáž obličeje", desc: "Zaměřuje se na tonizaci a posílení svalů, zvyšuje pružnost pleti a zvýrazňuje kontury.", min: 45, price: 800 },
      { name: "Masáž Gua Sha", desc: "Drenážní a konturovací procedura, která uvolňuje napětí a zlepšuje tonus pleti tradičními technikami gua sha.", min: 45, price: 800 },
      { name: "Bukální masáž", desc: "Technika masáže obličeje prováděná zvenčí i přes ústní dutinu. Pomáhá uvolnit napětí svalů obličeje, zlepšit mikrocirkulaci, zvýšit tonus pleti a zpřesnit kontury obličeje. Podporuje přirozené omlazení a hlubokou relaxaci.", min: 30, price: 800 },
      { name: "Alginátová maska · doplněk", desc: "Zmírňuje otoky a zarudnutí, sjednocuje tón pleti, hloubkově hydratuje a zklidňuje.", min: 15, price: 250 },
      { name: "Masáž hlavy", desc: "Uvolňuje nervový systém, stimuluje růst vlasů, snižuje stres a pomáhá předcházet bolestem hlavy.", min: 30, price: 600 },
    ],
    body: [
      { name: "Sportovní masáž", desc: "Regenerace svalů po fyzické zátěži a intenzivním tréninku — uvolňuje napětí, zmírňuje bolestivost, urychluje zotavení.", min: 60, price: 1600 },
      { name: "Masáž bambusovými metličkami", desc: "Tělo je jemně prohřáto a masírováno bambusovými metličkami — zlepšuje oběh, tok lymfy i tonus pleti.", min: 60, price: 1600 },
      { name: "Lymfodrenážní masáž", desc: "Zlepšuje tok lymfy, zmírňuje otoky, podporuje metabolismus a celkovou pohodu.", min: 60, price: 1500 },
      { name: "Anticelulitidová masáž", desc: "Intenzivní práce na problémových partiích — zlepšuje prokrvení, stimuluje odbourávání tuku, zpevňuje pokožku.", min: 45, price: 1500 },
      { name: "Medová masáž", desc: "Přírodní med čistí pokožku a aktivuje metabolismus — pleť je hladší, jemnější a svěží.", min: 60, price: 1500 },
      { name: "Klasická masáž", desc: "Univerzální procedura pro relaxaci a celkovou pohodu — zlepšuje prokrvení a obnovuje energii.", min: 60, price: 1300 },
      { name: "Aroma masáž", desc: "Klasické techniky s individuálně vybranými esenciálními oleji — hluboce uvolňuje, snižuje stres, zlepšuje náladu.", min: 60, price: 1300 },
      { name: "Vakuová (baňková) masáž těla", desc: "Baňky aktivně stimulují krevní a lymfatický oběh — zmírňují otoky, působí proti celulitidě.", min: 45, price: 1200 },
      { name: "Masáž zad", desc: "Uvolňuje napětí ve svalech zad, zmírňuje bolest a únavu, zlepšuje prokrvení a přináší hlubokou relaxaci a pocit lehkosti v těle.", min: 30, price: 700 },
      { name: "Reflexní masáž chodidel", desc: "Technika působení na biologicky aktivní body a zóny těla spojené s vnitřními orgány a soustavami. Stimulace těchto bodů aktivuje přirozené procesy regenerace a celkové uvolnění organismu.", min: 30, price: 600 },
    ],
  },

  /* -------------------- РУССКИЙ -------------------- */
  ru: {
    currency: (p) => p.toLocaleString("cs-CZ").replace(/\u00a0/g, " ") + " Kč",
    minLabel: "мин",
    strings: {
      navServices: "Услуги", navPrices: "Прайс-лист", navAbout: "Обо мне", navContact: "Контакты",
      heroEyebrow: "Massage 4 Beauty · Прага",
      heroH1: "Здоровая, сияющая кожа начинается с нежного прикосновения",
      heroSub: "Профессиональный массаж лица и тела от Людмилы — более десяти лет опыта, индивидуальные техники, заметный результат.",
      ctaBook: "Записаться", ctaPrices: "Смотреть прайс",
      aboutEyebrow: "Обо мне", aboutName: "Людмила Емельянова",
      aboutWelcome: "Добро пожаловать в Massage 4 Beauty.",
      aboutP1: "Меня зовут Людмила, и уже более десяти лет я помогаю своим клиентам находить гармонию, расслабление и естественную красоту с помощью профессионального массажа лица и тела.",
      aboutP2: "Каждая процедура уникальна и адаптируется к вашим индивидуальным потребностям. Независимо от того, ищете ли вы глубокое расслабление, облегчение напряжения, восстановление организма или естественное омоложение кожи, мы вместе подберём уход, который подойдёт именно вам.",
      aboutP3: "Моя цель — чтобы после процедуры вы уходили не только с ощущением лёгкости и отдыха, но и с новым зарядом энергии, более здоровой кожей и большей гармонией тела и души.",
      aboutCaption: "Сертифицированный массажист · Прага",
      pricesEyebrow: "Прайс-лист", pricesH2: "Процедуры и цены",
      groupFace: "Лицо", groupBody: "Тело",
      contactEyebrow: "Контакты", contactH2: "Запишитесь на визит",
      contactSub: "Напишите нам — поможем выбрать процедуру и удобное время визита.",
      lblAddress: "Адрес", lblPhone: "Телефон", lblEmail: "E-mail",
      fName: "Ваше имя", fContact: "Телефон или e-mail", fTreatment: "Процедура (по желанию)", fMessage: "Сообщение", fSend: "Отправить заявку",
      formThanks: "Спасибо! Мы скоро с вами свяжемся.",
      footerCopy: "© 2026 Beauty Massage · Людмила Емельянова",
      privacyLink: "Политика конфиденциальности",
      privacyEyebrow: "Правовая информация",
      privacyH1: "Политика конфиденциальности (GDPR)",
      privacyIntro1: "Контролёром персональных данных является Людмила Емельянова, осуществляющая деятельность под брендом Massage 4 Beauty, ИЧО: 23110716.",
      privacyIntro2: "Мы обрабатываем ваши персональные данные в следующем объёме: фамилия и имя, номер телефона, адрес электронной почты и иные данные, указанные в форме бронирования.",
      privacyH2Purpose: "Цели обработки данных",
      privacyP1: "создание и управление бронированием",
      privacyP2: "коммуникация по вопросам записи",
      privacyP3: "предоставление массажных и сопутствующих услуг",
      privacyP4: "решение вопросов изменения или отмены бронирования",
      privacyH2Legal: "Правовое основание обработки",
      privacyL1: "исполнение договора (бронирование и оказание услуги)",
      privacyL2: "законный интерес контролёра",
      privacyH2Retention: "Срок хранения данных",
      privacyRetention: "Мы храним персональные данные в течение необходимого времени — как правило, на протяжении всего периода сотрудничества и не более 3 лет после последнего бронирования.",
      privacyH2Recipients: "Получатели данных",
      privacyRecipients: "Персональные данные не передаются третьим лицам, за исключением технических поставщиков услуг.",
      privacyH2Marketing: "Маркетинговые соглашения (по желанию)",
      privacyPhotoLabel: "Согласие на использование фотографий",
      privacyCommLabel: "Согласие на маркетинговую коммуникацию",
      privacyH2Contact: "Контактная информация",
      privacyContactNote: "По вопросам защиты персональных данных вы можете связаться с нами через контактные данные, указанные на сайте.",
    },
    facial: [
      { name: "Ритуал для лица — шея, декольте, лицо и голова", desc: "Глубокая многоуровневая процедура: снимает мышечное напряжение, улучшает крово- и лимфообращение, естественно восстанавливает тонус кожи.", min: 60, price: 1600 },
      { name: "Миофасциальный массаж лица", desc: "Интенсивная работа с мышцами лица, включая внутреннюю поверхность щёк. Моделирует контур, уменьшает носогубные складки и провисание.", min: 45, price: 1300 },
      { name: "Массаж шеи, декольте и рук", desc: "Улучшает кровоток и лимфодренаж, расслабляет мышцы шеи и грудного отдела.", min: 60, price: 1200 },
      { name: "Лифтинг-массаж", desc: "Уменьшает отёчность и «мешки» под глазами, улучшает лимфодренаж, придаёт лицу более лёгкий, подтянутый вид.", min: 45, price: 1000 },
      { name: "Вакуумный (баночный) массаж лица", desc: "Тонизирует и укрепляет мышцы, повышает упругость кожи и выразительность контуров.", min: 45, price: 800 },
      { name: "Массаж гуаша", desc: "Дренажный и контурирующий эффект: снимает напряжение и улучшает тонус кожи традиционными техниками гуаша.", min: 45, price: 800 },
      { name: "Буккальный массаж", desc: "техника массажа лица, выполняемая как снаружи, так и через ротовую полость. Помогает снять напряжение лицевых мышц, улучшить микроциркуляцию, повысить тонус кожи и сделать контуры лица более четкими. Способствует естественному омоложению и расслаблению.", min: 30, price: 800 },
      { name: "Альгинатная маска · дополнение", desc: "Снимает отёчность и покраснения, выравнивает тон, глубоко увлажняет и успокаивает кожу.", min: 15, price: 250 },
       { name: "Массаж головы", desc: "Расслабляет нервную систему, стимулирует рост волос, снижает стресс и помогает предотвращать головные боли.", min: 30, price: 600 },
    ],
    body: [
      { name: "Спортивный массаж", desc: "Восстановление мышц после нагрузок и интенсивных тренировок — снимает напряжение, уменьшает болезненность, ускоряет восстановление.", min: 60, price: 1600 },
      { name: "Массаж бамбуковыми вениками", desc: "Тело мягко прогревается и массируется бамбуковыми вениками — улучшаются кровообращение, лимфоток и тонус кожи.", min: 60, price: 1600 },
      { name: "Лимфодренажный массаж", desc: "Улучшает лимфоток, уменьшает отёки, поддерживает обмен веществ и общее самочувствие.",min: 60, price: 1500 },
      { name: "Антицеллюлитный массаж", desc: "Интенсивная работа с проблемными зонами — улучшает кровообращение, стимулирует расщепление жира, повышает упругость кожи.", min: 45, price: 1500 },
      { name: "Медовый массаж", desc: "Натуральный мёд очищает кожу и активизирует обмен веществ — кожа становится более гладкой, мягкой и свежей.", min: 60, price: 1500 },
      { name: "Классический массаж", desc: "Универсальная процедура для расслабления и общего оздоровления — улучшает кровообращение и восстанавливает силы.", min: 60, price: 1300 },
      { name: "Арома-массаж", desc: "Классические техники с индивидуально подобранными эфирными маслами — глубоко расслабляет, снижает стресс, улучшает настроение.", min: 60, price: 1300 },
      { name: "Вакуумный (баночный) массаж тела", desc: "Банки активно стимулируют крово- и лимфообращение — уменьшают отёки, борются с целлюлитом.", min: 45, price: 1200 },
      { name: "Массаж cпины", desc: "Снимает напряжение в мышцах спины, уменьшает боль и усталость, улучшает кровообращение и приносит глубокое расслабление и ощущение лёгкости в теле.", min: 30, price: 700 },
      { name: "Рефлекторный массаж стоп", desc: "Техника воздействия на биологически активные точки и зоны тела, которые связаны с внутренними органами и системами организма. Стимуляция этих точек  активизирует естественные процессы регенерации и общее расслабление организма.", min: 30, price: 600 },
    ],
  },
};
