/* ============================================================
   Massage 4 Beauty — site content in 3 languages.
   Edit text and prices here. Prices are numbers (CZK).
   ============================================================ */
window.CONTENT = {
  contact: {
    address: "Děkanská vinice I 819/16, Praha 4 – Nusle",
    phone: "+420 721 761 411",
    email: "beautymassage.prague@gmail.com",
  },

  /* -------------------- ENGLISH -------------------- */
  en: {
    currency: (p) => p.toLocaleString("en-US") + " CZK",
    minLabel: "min",
    strings: {
      navServices: "Services", navPrices: "Price list", navAbout: "About", navContact: "Contact",
      heroEyebrow: "Massage 4 Beauty · Prague",
      heroH1: "Healthy, glowing skin begins with a gentle touch",
      heroSub: "Professional facial and body massage by Ludmila — over ten years of experience, personalised techniques, visible results.",
      ctaBook: "Book an appointment", ctaPrices: "View price list",
      aboutEyebrow: "About the master", aboutName: "Ludmila Yemelianova",
      aboutP1: "My name is Ludmila, and I am a massage therapist with over 10 years of experience. My clients achieve balance and well-being through personalised massage techniques tailored to their individual skin needs.",
      aboutP2: "Let's take care of your skin and give your face a lift — start your journey to beautiful, healthier skin today.",
      aboutCaption: "Certified massage therapist · Prague",
      pricesEyebrow: "Price list", pricesH2: "Treatments & pricing",
      groupFace: "Face", groupBody: "Body",
      contactEyebrow: "Contact", contactH2: "Book your visit",
      contactSub: "Leave a message and we'll help you pick the right treatment and a convenient date and time.",
      lblAddress: "Address", lblPhone: "Phone", lblEmail: "Email",
      fName: "Your name", fContact: "Phone or email", fTreatment: "Treatment (optional)", fMessage: "Message", fSend: "Send request",
      formThanks: "Thank you! We'll get back to you shortly.",
      footerCopy: "© 2026 Beauty Massage by Ludmila Yemelianova",
    },
    facial: [
      { name: "Facial Ritual — Neck, Décolleté, Face & Head", desc: "A deep, multi-level procedure releasing muscle tension, improving blood and lymph circulation, and naturally restoring skin tone.", min: 60, price: 1600 },
      { name: "Myofascial Facial Massage", desc: "Intensive work with facial muscles, including the inner cheek area. Sculpts the contour, reduces nasolabial folds and sagging.", min: 45, price: 1300 },
      { name: "Neck, Décolleté & Hands Massage", desc: "Improves blood flow and lymph drainage while relaxing the muscles of the neck and chest area.", min: 60, price: 1200 },
      { name: "Lifting Massage", desc: "Reduces puffiness under the eyes, improves lymphatic drainage, gives the face a lighter, more lifted appearance.", min: 45, price: 1000 },
      { name: "Vacuum (Cupping) Facial Massage", desc: "Focuses on muscle toning and strengthening, enhancing skin elasticity and facial contours.", min: 45, price: 800 },
      { name: "Gua Sha Massage", desc: "A draining, contouring treatment that relieves tension and enhances skin tone using traditional Gua Sha techniques.", min: 45, price: 800 },
      { name: "Alginate Mask · add-on", desc: "Reduces swelling and redness, evens out skin tone, deeply moisturises and soothes the skin.", min: 15, price: 250 },
    ],
    body: [
      { name: "Sports Massage", desc: "Muscle recovery after exertion and intense training — relieves tension, reduces soreness, speeds up recovery.", price: 1600 },
      { name: "Massage with Bamboo Brooms", desc: "The body is gently warmed and massaged with bamboo brooms, improving circulation, lymph flow and skin tone.", price: 1600 },
      { name: "Lymphatic Drainage Massage", desc: "Improves lymph flow, reduces swelling and puffiness, supports metabolism and overall well-being.", price: 1500 },
      { name: "Anti-Cellulite Massage", desc: "Intensive work on problem areas — improves circulation, stimulates fat breakdown, increases skin firmness.", price: 1500 },
      { name: "Honey Massage", desc: "Natural honey cleanses the skin and activates metabolism, leaving skin smoother, softer and refreshed.", price: 1500 },
      { name: "Classic Massage", desc: "A universal procedure for relaxation and overall wellness — improves circulation and restores energy.", price: 1300 },
      { name: "Aroma Massage", desc: "Classic techniques with individually selected essential oils — deeply relaxing, lowers stress, improves mood.", price: 1300 },
      { name: "Vacuum (Cupping) Body Massage", desc: "Suction cups actively stimulate blood and lymph circulation — reduces swelling, fights cellulite.", price: 1200 },
    ],
  },

  /* -------------------- ČEŠTINA -------------------- */
  cs: {
    currency: (p) => p.toLocaleString("cs-CZ").replace(/\u00a0/g, " ") + " Kč",
    minLabel: "min",
    strings: {
      navServices: "Služby", navPrices: "Ceník", navAbout: "O mně", navContact: "Kontakt",
      heroEyebrow: "Massage 4 Beauty · Praha",
      heroH1: "Zdravá, zářivá pleť začíná jemným dotekem",
      heroSub: "Profesionální masáže obličeje a těla od Ludmily — více než deset let zkušeností, individuální techniky, viditelné výsledky.",
      ctaBook: "Objednat se", ctaPrices: "Zobrazit ceník",
      aboutEyebrow: "O mně", aboutName: "Ludmila Yemelianova",
      aboutP1: "Jmenuji se Ludmila a jsem masérka s více než desetiletou praxí. Mí klienti dosahují rovnováhy a pohody díky individuálním masážním technikám přizpůsobeným potřebám jejich pleti.",
      aboutP2: "Postarejme se o vaši pleť a dopřejme obličeji lifting — začněte svou cestu ke zdravější pleti ještě dnes.",
      aboutCaption: "Certifikovaná masérka · Praha",
      pricesEyebrow: "Ceník", pricesH2: "Procedury a ceny",
      groupFace: "Obličej", groupBody: "Tělo",
      contactEyebrow: "Kontakt", contactH2: "Objednejte se",
      contactSub: "Napište nám a pomůžeme vám vybrat vhodnou proceduru i termín návštěvy.",
      lblAddress: "Adresa", lblPhone: "Telefon", lblEmail: "E-mail",
      fName: "Vaše jméno", fContact: "Telefon nebo e-mail", fTreatment: "Procedura (volitelné)", fMessage: "Zpráva", fSend: "Odeslat poptávku",
      formThanks: "Děkujeme! Brzy se vám ozveme.",
      footerCopy: "© 2026 Beauty Massage · Ludmila Yemelianova",
    },
    facial: [
      { name: "Rituál pro obličej — krk, dekolt, obličej a hlava", desc: "Hluboká vícevrstvá procedura uvolňující svalové napětí, zlepšující krevní i lymfatický oběh a přirozeně obnovující tonus pleti.", min: 60, price: 1600 },
      { name: "Myofasciální masáž obličeje", desc: "Intenzivní práce s obličejovými svaly včetně vnitřní strany tváří. Modeluje konturu, redukuje nosoretní rýhy a povadlost.", min: 45, price: 1300 },
      { name: "Masáž krku, dekoltu a rukou", desc: "Zlepšuje prokrvení a lymfatickou drenáž a uvolňuje svaly krku a hrudníku.", min: 60, price: 1200 },
      { name: "Liftingová masáž", desc: "Redukuje otoky pod očima, zlepšuje lymfatickou drenáž a dodává obličeji lehčí, vypnutější vzhled.", min: 45, price: 1000 },
      { name: "Vakuová (baňková) masáž obličeje", desc: "Zaměřuje se na tonizaci a posílení svalů, zvyšuje pružnost pleti a zvýrazňuje kontury.", min: 45, price: 800 },
      { name: "Masáž Gua Sha", desc: "Drenážní a konturovací procedura, která uvolňuje napětí a zlepšuje tonus pleti tradičními technikami gua sha.", min: 45, price: 800 },
      { name: "Alginátová maska · doplněk", desc: "Zmírňuje otoky a zarudnutí, sjednocuje tón pleti, hloubkově hydratuje a zklidňuje.", min: 15, price: 250 },
    ],
    body: [
      { name: "Sportovní masáž", desc: "Regenerace svalů po fyzické zátěži a intenzivním tréninku — uvolňuje napětí, zmírňuje bolestivost, urychluje zotavení.", price: 1600 },
      { name: "Masáž bambusovými metličkami", desc: "Tělo je jemně prohřáto a masírováno bambusovými metličkami — zlepšuje oběh, tok lymfy i tonus pleti.", price: 1600 },
      { name: "Lymfodrenážní masáž", desc: "Zlepšuje tok lymfy, zmírňuje otoky, podporuje metabolismus a celkovou pohodu.", price: 1500 },
      { name: "Anticelulitidová masáž", desc: "Intenzivní práce na problémových partiích — zlepšuje prokrvení, stimuluje odbourávání tuku, zpevňuje pokožku.", price: 1500 },
      { name: "Medová masáž", desc: "Přírodní med čistí pokožku a aktivuje metabolismus — pleť je hladší, jemnější a svěží.", price: 1500 },
      { name: "Klasická masáž", desc: "Univerzální procedura pro relaxaci a celkovou pohodu — zlepšuje prokrvení a obnovuje energii.", price: 1300 },
      { name: "Aroma masáž", desc: "Klasické techniky s individuálně vybranými esenciálními oleji — hluboce uvolňuje, snižuje stres, zlepšuje náladu.", price: 1300 },
      { name: "Vakuová (baňková) masáž těla", desc: "Baňky aktivně stimulují krevní a lymfatický oběh — zmírňují otoky, působí proti celulitidě.", price: 1200 },
    ],
  },

  /* -------------------- РУССКИЙ -------------------- */
  ru: {
    currency: (p) => p.toLocaleString("cs-CZ").replace(/\u00a0/g, " ") + " Kč",
    minLabel: "мин",
    strings: {
      navServices: "Услуги", navPrices: "Прайс-лист", navAbout: "Обо мне", navContact: "Контакты",
      heroEyebrow: "Massage 4 Beauty · Прага",
      heroH1: "Здоровая, сияющая кожа начинается с нежного прикосновения",
      heroSub: "Профессиональный массаж лица и тела от Людмилы — более десяти лет опыта, индивидуальные техники, заметный результат.",
      ctaBook: "Записаться", ctaPrices: "Смотреть прайс",
      aboutEyebrow: "Обо мне", aboutName: "Людмила Емельянова",
      aboutP1: "Меня зовут Людмила, я массажист с более чем десятилетним опытом. Мои клиенты обретают баланс и хорошее самочувствие благодаря индивидуальным техникам массажа, подобранным под потребности кожи.",
      aboutP2: "Позаботимся о вашей коже и подарим лицу лифтинг — начните путь к здоровой коже уже сегодня.",
      aboutCaption: "Сертифицированный массажист · Прага",
      pricesEyebrow: "Прайс-лист", pricesH2: "Процедуры и цены",
      groupFace: "Лицо", groupBody: "Тело",
      contactEyebrow: "Контакты", contactH2: "Запишитесь на визит",
      contactSub: "Напишите нам — поможем выбрать процедуру и удобное время визита.",
      lblAddress: "Адрес", lblPhone: "Телефон", lblEmail: "E-mail",
      fName: "Ваше имя", fContact: "Телефон или e-mail", fTreatment: "Процедура (по желанию)", fMessage: "Сообщение", fSend: "Отправить заявку",
      formThanks: "Спасибо! Мы скоро с вами свяжемся.",
      footerCopy: "© 2026 Beauty Massage · Людмила Емельянова",
    },
    facial: [
      { name: "Ритуал для лица — шея, декольте, лицо и голова", desc: "Глубокая многоуровневая процедура: снимает мышечное напряжение, улучшает крово- и лимфообращение, естественно восстанавливает тонус кожи.", min: 60, price: 1600 },
      { name: "Миофасциальный массаж лица", desc: "Интенсивная работа с мышцами лица, включая внутреннюю поверхность щёк. Моделирует контур, уменьшает носогубные складки и провисание.", min: 45, price: 1300 },
      { name: "Массаж шеи, декольте и рук", desc: "Улучшает кровоток и лимфодренаж, расслабляет мышцы шеи и грудного отдела.", min: 60, price: 1200 },
      { name: "Лифтинг-массаж", desc: "Уменьшает отёчность и «мешки» под глазами, улучшает лимфодренаж, придаёт лицу более лёгкий, подтянутый вид.", min: 45, price: 1000 },
      { name: "Вакуумный (баночный) массаж лица", desc: "Тонизирует и укрепляет мышцы, повышает упругость кожи и выразительность контуров.", min: 45, price: 800 },
      { name: "Массаж гуаша", desc: "Дренажный и контурирующий эффект: снимает напряжение и улучшает тонус кожи традиционными техниками гуаша.", min: 45, price: 800 },
      { name: "Альгинатная маска · дополнение", desc: "Снимает отёчность и покраснения, выравнивает тон, глубоко увлажняет и успокаивает кожу.", min: 15, price: 250 },
    ],
    body: [
      { name: "Спортивный массаж", desc: "Восстановление мышц после нагрузок и интенсивных тренировок — снимает напряжение, уменьшает болезненность, ускоряет восстановление.", price: 1600 },
      { name: "Массаж бамбуковыми вениками", desc: "Тело мягко прогревается и массируется бамбуковыми вениками — улучшаются кровообращение, лимфоток и тонус кожи.", price: 1600 },
      { name: "Лимфодренажный массаж", desc: "Улучшает лимфоток, уменьшает отёки, поддерживает обмен веществ и общее самочувствие.", price: 1500 },
      { name: "Антицеллюлитный массаж", desc: "Интенсивная работа с проблемными зонами — улучшает кровообращение, стимулирует расщепление жира, повышает упругость кожи.", price: 1500 },
      { name: "Медовый массаж", desc: "Натуральный мёд очищает кожу и активизирует обмен веществ — кожа становится более гладкой, мягкой и свежей.", price: 1500 },
      { name: "Классический массаж", desc: "Универсальная процедура для расслабления и общего оздоровления — улучшает кровообращение и восстанавливает силы.", price: 1300 },
      { name: "Арома-массаж", desc: "Классические техники с индивидуально подобранными эфирными маслами — глубоко расслабляет, снижает стресс, улучшает настроение.", price: 1300 },
      { name: "Вакуумный (баночный) массаж тела", desc: "Банки активно стимулируют крово- и лимфообращение — уменьшают отёки, борются с целлюлитом.", price: 1200 },
    ],
  },
};
